<?php
/** LiangLeeBlockUser
 * Block a username
 * @package LiangLeeFramework
 * @subpackage  LiangLeeBlockuser 
 * @author Liang Lee
 * @copyright Copyright 2013, Liang Lee
 * @ide The Code is Generated by Liang Lee php IDE.
 * @File en.php
 */		
 echo '<div id="wait">';
echo '<h2>'.elgg_echo('blockuser').'</h2>';		
echo '<p>'.elgg_echo('block:user:ajax:message:1').'</p>';
echo '<p>'.elgg_echo('block:user:ajax:message:2').'</p>';
echo elgg_view('input/submit', array('value' => elgg_echo('block')));
echo '</div>';