<?php
/** LiangLeeBlockUser
 * Block a username
 * @package LiangLeeFramework
 * @subpackage  LiangLeeBlockuser 
 * @author Liang Lee
 * @copyright Copyright 2013, Liang Lee
 * @ide The Code is Generated by Liang Lee php IDE.
 * @File en.php
 */
$english = array(
'lee:block:plc' => "Enter username seprate by comma ',' ",
'blockuser' => 'Block user',
'lee:blockuser:block' => 'Block a user, to block mean, a blocked user can not access your profile or send you a message. Enter a username of a user you want to block enter like this username1, username2, username3',
//@todo why html tags here, $waynelee
'usernames:block' => "<h2>Blocked User's</h2>",
'error' => 'Unexcepted Error',
'block:add:msg' => 'The user %s added to your block list please save settings.',
'block:user:exsit' => 'This user is already in your block list.',
'block:user:ok' => 'The user is now blocked!.',
'block' => 'Block',
'block:error:msg' => "Sorry the page you are requested is not found or you don't have premission to view that page",

 );
					
add_translation("en", $english);
