<?php
/** LiangLeeBlockUser
* Block a username
* @package LiangLeeFramework
* @subpackage LiangLeeBlockuser
* @author Liang Lee
* @copyright Copyright 2013, Liang Lee
* @ide The Code is Generated by Liang Lee php IDE.
* @File en.php
*/
$english = array(
'lee:block:plc' => "Enter username(s) seperated by a comma ',' ",
'blockuser' => 'Block user',
'lee:blockuser:block' => 'Block a user, which means a blocked user can not access your profile or send you a message. Enter the username(s) of the user(s) you wish to block, such as like this username1, username2, username3',
//@todo why html tags here, $waynelee
'usernames:block' => "<h2>Blocked User's</h2>",
'error' => 'You have been Blocked!',
'block:add:msg' => 'The user %s was added to your block list, please save the settings.',
'block:user:exsit' => 'This user is already in your block list.',
'block:user:ok' => 'The user is now blocked!.',
'block' => 'Block',
'block:error:msg' => "Sorry! This member has blocked you , you can not access that page.",
'block:user:ajax:message:1' => 'If you find this is a fake user, or they are posting spam, please report them to the Administrator.',
'block:user:ajax:message:2' => 'Are you sure you want to block this user?',
'block:user:ajax:message:3' => 'View Blocklist',
);

add_translation("en", $english);