<?php
/** LiangLeeBlockUser
 * Block a username
 * @package LiangLeeFramework
 * @subpackage  LiangLeeBlockuser 
 * @author Liang Lee
 * @copyright Copyright 2013, Liang Lee
 * @ide The Code is Generated by Liang Lee php IDE.
 * @File api.php
 */
echo "<script type=\"text/javascript\">\n"; 
echo "$(document).ready(function() {\n"; 
echo "$(\"#lianglee_blockuser_load\").fancybox({\n"; 
echo "'titlePosition':'inside',\n"; 
echo "'transitionIn':'none',\n"; 
echo "'transitionOut':'none'\n"; 
echo "});\n"; 
echo "});\n"; 
echo "	</script>\n";
echo LiangLee_inc_js('LiangleeFramework','jquery/fancybox/jquery.mousewheel-3.0.4.pack.js');
echo LiangLee_inc_css('LiangleeFramework','vendors/jquery/fancybox/jquery.fancybox-1.3.4.css');
echo LiangLee_inc_js('LiangleeFramework','jquery/fancybox/jquery.fancybox-1.3.4.pack.js');
echo '<div style="display: none;">';
echo '<div id="lianglee_blockuser" style="min-width:320px;max-height:125px;overflow:auto;">';
echo lee_blockuser_view_ajax();
echo '</div></div>';



