<?php
/** LiangLeeBlockUser
 * Block a username
 * @package LiangLeeFramework
 * @subpackage  LiangLeeBlockuser 
 * @author Liang Lee
 * @copyright Copyright 2013, Liang Lee
 * @ide The Code is Generated by Liang Lee php IDE.
 * @File css.php
 */
?>
/* LiangLeeBlockUser CSS Starts */

.LiangLee_blockuser_list{
padding: 3px;
margin-bottom: -5px;
}
.LiangLee_blockuser_listdata{
border-bottom:#E0E0E0 solid 1px; 
border-top:#E0E0E0 solid 1px;
background:#F5F5F5;
}
.LiangLee_blockuser_msg{
border:#FFFF99 solid 2px;
background: #FFFFCC;
height:40px;
}
.LiangLee_blockuser_msg-text{
margin: 10px 15px 4px;
font-weight: bold;
}
.LiangLee_blockuser_view_icon{
background:url(<?php echo lee_baseurl;?>mod/blockuser/media/icon_blockUser.gif) center left no-repeat;
padding:0 0 0 21px;
white-space:nowrap;
text-decoration:none;
}
/* LiangLeeBlockUser CSS Ends */
