<?php
/** LiangLeeBlockUser
 * Block a username
 * @package LiangLeeFramework
 * @subpackage  LiangLeeBlockuser 
 * @author Liang Lee
 * @copyright Copyright 2013, Liang Lee
 * @ide The Code is Generated by Liang Lee php IDE.
 * @File view_button.php
 */

if (elgg_is_logged_in()){
if (!elgg_in_context('widgets') && elgg_in_context('profile') && lee_loggedin_entity_guid != elgg_get_page_owner_entity()->guid) { 
echo '<div class="LiangLee_blockuser_view_box"><div><span>';
echo '<div class="LiangLee_blockuser_view_box_text">';
echo '<a id="lianglee_blockuser_load" class="LiangLee_blockuser_view_icon" href="#lianglee_blockuser">'.elgg_echo('blockuser').'</a>';
echo '</div></span></div></div>';
   }
} 
