<?php
/** LiangLeeBlockUser
 * Block a username
 * @package LiangLeeFramework
 * @subpackage  LiangLeeBlockuser 
 * @author Liang Lee
 * @copyright Copyright 2013, Liang Lee
 * @ide The Code is Generated by Liang Lee php IDE.
 * @File usersettings.php
 */
 
$plugin = elgg_get_plugin_from_id('blockuser');
echo elgg_view('forms/blockuser/settings_user' , array('plugin' => $plugin));

